server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    # 表示是否将自己注册进EurekaService
    register-with-eureka: true
    # 是否从EurekaService 抓取已有的注册信息，默认为true. 单点可以随意，集群必须为true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
