server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:zhj52666/spring-cloud-study.git
          search-paths:
            - spring-cloud-study/spring-cloud-config
          label: master

eureka:
  client:
    # 表示是否将自己注册进EurekaService
    register-with-eureka: false
    # 是否从EurekaService 抓取已有的注册信息，默认为true. 单点可以随意，集群必须为true
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/ # 单机版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ # 集群版


