server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment
  zipkin:
    base-url: http://master:9411
  sleuth:
    sampler:
      # 采样率在0-1之间，1 则表示全部采集
      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://zhj.com:3306/cloud_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: zhjroot

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhj.springcloud.entity

eureka:
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    # 受到最后一次心跳后等待时间上限，默认是90秒，超时就删除服务
    lease-renewal-interval-in-seconds: 30
  client:
    # 表示是否将自己注册进EurekaService
    register-with-eureka: true
    # 是否从EurekaService 抓取已有的注册信息，默认为true. 单点可以随意，集群必须为true
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/ # 单机版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ # 集群版
