server:
  port: 9002

spring:
  application:
    name: nacos-provider-payment
  cloud:
    nacos:
      discovery:
        # server-addr: localhost:8848
        server-addr: slave05:1111

management:
  endpoints:
    web:
      exposure:
        include: "*"




