server:
  port: 9527

spring:
  application:
    name: cloud-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: payment_routh_01
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/get/**
#
#        - id: payment_routh_02
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/lb/**
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh_01
          # uri: http://localhost:8001
          uri: lb://cloud-provider-payment
          predicates:
            - Path=/payment/get/**
            - After=2021-05-16T19:58:19.577+08:00[Asia/Shanghai]
            #- Between=2021-05-16T19:58:19.577+08:00[Asia/Shanghai],2021-05-16T19:58:19.577+08:00[Asia/Shanghai]
            #- Before=2021-05-16T19:58:19.577+08:00[Asia/Shanghai]

        - id: payment_routh_02
          uri: lb://cloud-provider-payment
          predicates:
            - Path=/payment/lb/**
            #- Host=**.zhj.com
            #- Cookie=username,zhj
            #- Header=X-Request-Id, \d+

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    # 表示是否将自己注册进EurekaService
    register-with-eureka: true
    # 是否从EurekaService 抓取已有的注册信息，默认为true. 单点可以随意，集群必须为true
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/ # 单机版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ # 集群版
