server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: aliyun:2181
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: org.gjt.mm.mysql.Driver
#    url: jdbc:mysql://zhj.com:3306/cloud_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: zhjroot

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.zhj.springcloud.entity

